import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./SharedCompoment/Navbar";

const roboto = Roboto({
  className: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Faketube - Watch Videos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
